version: '3.9'
# If using colima as docker runtime on osx, then set WORKDIR so volume mounts work.
# WORKDIR=`pwd` docker-compose up
services:
  cube_api:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
    environment:
      - CUBEJS_LOG_LEVEL=info
      - DEBUG_LOG=true
      - CUBEJS_API_SECRET=secret1234
      - CUBEJS_DB_TYPE=duckdb
      # - CUBEJS_EXTERNAL_DEFAULT=true
      # - CUBEJS_SCHEDULED_REFRESH_DEFAULT=true
      - CUBEJS_DEV_MODE=true
      - CUBEJS_SQL_USER=myusername
      - CUBEJS_SQL_PASSWORD=mypassword
    volumes:
      - ${PWD}:/cube/conf
      - ${PWD}/mode:/cube/model
